DELETE from TEFLOW_BASE_DATA_DETAIL WHERE MASTER_ID = '10205'
INSERT TEFLOW_BASE_DATA_DETAIL(MASTER_ID,OPTION_VALUE,option_label,STATUS)  VALUES('10205','INFORMATION IS NULL','INFORMATION IS NULL',NULL)
INSERT TEFLOW_BASE_DATA_DETAIL(MASTER_ID,OPTION_VALUE,option_label,STATUS)  VALUES('10205','MESSAGE IS NULL','MESSAGE IS NULL',NULL)
INSERT TEFLOW_BASE_DATA_DETAIL(MASTER_ID,OPTION_VALUE,option_label,STATUS)  VALUES('10205','PERSONAL INFORMATION IS NULL','PERSONAL INFORMATION IS NULL',NULL)

set identity_insert [TEFLOW_BASE_DATA_MASTER] on
DELETE FROM TEFLOW_BASE_DATA_MASTER WHERE MASTER_ID = '10205'

INSERT TEFLOW_BASE_DATA_MASTER(MASTER_ID,field_name,TYPE_CODE)  VALUES('10205','Reject Reason','1')
set identity_insert [TEFLOW_BASE_DATA_MASTER] off