
--DROP TABLE TNOVA_SDMemPremDtl

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.TNOVA_SDMemPremDtl'))
BEGIN
	CREATE TABLE dbo.TNOVA_SDMemPremDtl(
		NOVAREQNO	VARCHAR(30)	NOT NULL,
		POLNO	CHAR(10)	NOT NULL,
		BILLPRDFR	CHAR(10)	NOT NULL,
		STATE	CHAR(03)	NOT NULL,
		IdentifyID	VARCHAR(20)	NOT NULL,
		DOB	DATETIME	NULL,
		INIEFFDT	DATETIME	NULL,
		CHGSTATUS	VARCHAR(05)	NULL,
		PRODCODE	CHAR(5)	NULL,
		BenefitAmount	Decimal(11,0) NULL,
		PaidPrem	Decimal(13,2) NULL
	) 
	CREATE CLUSTERED INDEX IDX_TNOVA_SDMemPremDtl ON dbo.TNOVA_SDMemPremDtl (NOVAREQNO, POLNO, BILLPRDFR, STATE, IdentifyID,PRODCODE)
END

