if exists (select 1 from dbo.sysobjects where id = object_id(N'[dbo].[UspGNOVACompassClntCode]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
     drop procedure [dbo].[UspGNOVACompassClntCode]
GO

/*********************** REVISION LOG: ***********************************
Version			Date			Revised by				Remark
1.0				20150216		asnpg8q					initial
**************************************************************************/

CREATE PROCEDURE [dbo].[UspGNOVACompassClntCode]
AS
BEGIN
 
	SET NOCOUNT ON
	BEGIN TRAN	
	DECLARE @tempSysGenNum decimal(9,0)
	
	SELECT @tempSysGenNum = 100000 + SYSGENNUM FROM TSYSGENNUM WHERE TBLCODE = 'CL' AND RCDSTS = 'A'
	
	while exists(SELECT 1 FROM TCLIENT WHERE CLNTCODE = right(cast(@tempSysGenNum  as varchar(6)),5))
	begin
	   set @tempSysGenNum = @tempSysGenNum + 1
	end
	
	update TSYSGENNUM set SYSGENNUM = right(@tempSysGenNum+1,5) WHERE TBLCODE = 'CL' AND RCDSTS = 'A'
	
	INSERT TCLIENT(CLNTCODE,CLNTNAME,ADDRESS1,ADDRESS2,ADDRESS3,STATE,CNTYCODE,MAILCODE,TELNO,FAXNO,CONTPERSON,CONTITLE,SALARYMODE,SALARYCURC,SICCODE,PARENTCOMP,STATUS,STATEFFDT,DOCSEQ,GENCERTIND,GENCERTNUM,SUBOFFIND,PREMTAXIND,GENOSPRMNT,RCDSTS,RCDUSRID,RCDDTSTMP,BILLSEQNUM,ADDRESS4,EMAILADDR,BankCode,BankAC,TaxID,PAYEENAME,CLNTNAMEGEN,PRMRFBANKCODE,PRMRFBANKACCT,BANKBRNAME,PRMRFBANKBRNAME,DNBcode,AIGCLNTCODE,DISTRICT,CITY,CRITTYPE,CRITCODE,COMPNATURE,INDUSTRYCLS,NOOFMEMS,EXCLUDE,OPTOUTIND) 
	SELECT right(cast(@tempSysGenNum  as varchar(6)),5),N'NOVA Pending','XXXXX',ADDRESS2,ADDRESS3,STATE,CNTYCODE,MAILCODE,TELNO,FAXNO,'XXXXX',CONTITLE,SALARYMODE,SALARYCURC,SICCODE,PARENTCOMP,STATUS,STATEFFDT,DOCSEQ,GENCERTIND,GENCERTNUM,SUBOFFIND,PREMTAXIND,GENOSPRMNT,RCDSTS,RCDUSRID,RCDDTSTMP,BILLSEQNUM,ADDRESS4,EMAILADDR,BankCode,BankAC,TaxID,PAYEENAME,CLNTNAMEGEN,PRMRFBANKCODE,PRMRFBANKACCT,BANKBRNAME,PRMRFBANKBRNAME,DNBcode,AIGCLNTCODE,DISTRICT,CITY,CRITTYPE,CRITCODE,COMPNATURE,INDUSTRYCLS,NOOFMEMS,EXCLUDE,OPTOUTIND
	FROM NOVA.TCLIENT_TEMPLATE WHERE FORM_SYSTEM_ID=0

	select right(cast(@tempSysGenNum  as varchar(6)),5) as SYSGENNUM

	COMMIT

END
