IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.USPGNOVAGENTUHCMEMBERID') AND sysstat & 0xf = 4)
	drop procedure dbo.USPGNOVAGENTUHCMEMBERID
GO
SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER ON  
SET CONCAT_NULL_YIELDS_NULL ON 
SET ANSI_WARNINGS ON 
SET ANSI_PADDING ON
GO
CREATE PROCEDURE dbo.USPGNOVAGENTUHCMEMBERID
(@request_no		VARCHAR(30))
AS
BEGIN
/*******************************************************************
	COMPASS 2000 USER STORED PROCEDURE

	USPGNOVAGENTUHCMEMBERID.SQL - Prepare TMEMPTPOL table for TMEMPTPOL_NOVA letter
        
        PROCESSING DETAILS:
        Prepare TMEMPTPOL table for TMEMPTPOL_NOVA letter
			
	AUTHOR      :     Issca Zhu
	DATE	    :     11/06/2014
	PIRNO	    :	  

	REVISION LOG:
	VERSION	  PIRNO		PROGRAMMER	REMARK		DATE		PURPOSE
        5.0	  NOVA		Issca Zhu				11/06/2014	Initial Version
********************************************************************/
/*error handling variable section */
DECLARE @ErrFrom	CHAR(20)
DECLARE @ErrMsg		CHAR(65)
DECLARE @ErrData	CHAR(45)
DECLARE @ErrCode        INT
DECLARE @StoreProcInd   CHAR(1)
DECLARE	@cMSGID		CHAR(5)
/*DECLARE VARIABLES AND CONSTANTS*/
DECLARE	@cACTIVE	CHAR(1)
DECLARE	@cDELETED	CHAR(1)
DECLARE	@cYES		CHAR(1)
DECLARE	@cNO		CHAR(1)
DECLARE @XML XML 
DECLARE	@CLNTCODE	CHAR(1)
DECLARE	@cCLNTCODE	CHAR(5)
DECLARE	@cPOLNO		CHAR(10)
DECLARE	@cCERTNO	VARCHAR(10)
DECLARE @cProgramID VARCHAR(60)
DECLARE	@EFFDATE	DATETIME
DECLARE	@cMEM	CHAR(3)

SELECT @cACTIVE = 'A'
SELECT @cMEM = 'MEM'

SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER ON  
SET CONCAT_NULL_YIELDS_NULL ON 
SET ANSI_WARNINGS ON 
SET ANSI_PADDING ON

SELECT @XML = NovaXML FROM T_Nova_TXMLConvert where request_no = @request_no

declare CUR_GENMEMBERID cursor for
SELECT  T.N.value('CLNTCODE[1]','varchar(5)'), T.N.value('POLNO[1]','varchar(10)'),T.N.value('CERTNO[1]','varchar(10)'),T.N.value('INIEFFDT[1]','datetime') from  @XML.nodes('/form/TMEMPTPOL/item') T(N) 
open CUR_GENMEMBERID

FETCH NEXT FROM CUR_GENMEMBERID INTO @cCLNTCODE,@cPOLNO,@cCERTNO,@EFFDATE
WHILE (@@FETCH_STATUS = 0)
BEGIN

EXEC USP_HMEP001 @cCLNTCODE,@cCERTNO,@EFFDATE,@cPOLNO,@cMEM

SELECT @ErrCode = @@error
IF @ErrCode <> 0
BEGIN
	--SELECT @cRETCODE = '9999'
	
	INSERT T_Nova_ErrlogTran (RequestNo,ProgramID,ERRORLOG,RCDUSRID,RCDDTSTMP) 
	VALUES(@request_no,@cProgramID,'insert temp table TUHCMEMBERID error','NOVAPROC',GETDATE())
	
	GOTO EXIT_WINDOW
END	
	
FETCH NEXT FROM CUR_GENMEMBERID INTO @cCLNTCODE,@cPOLNO,@cCERTNO,@EFFDATE
END

CLOSE CUR_GENMEMBERID 
DEALLOCATE CUR_GENMEMBERID


EXIT_WINDOW:

SET ANSI_NULLS OFF 
SET QUOTED_IDENTIFIER OFF  
SET CONCAT_NULL_YIELDS_NULL OFF 
SET ANSI_WARNINGS OFF 
SET ANSI_PADDING OFF 

	RETURN

END

SET ANSI_NULLS OFF 
SET QUOTED_IDENTIFIER OFF  
SET CONCAT_NULL_YIELDS_NULL OFF 
SET ANSI_WARNINGS OFF 
SET ANSI_PADDING OFF 
GO