IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = object_id('dbo.UspGNOVASDLoadBillFrDt') and sysstat & 0xf = 4)
	DROP PROCEDURE dbo.UspGNOVASDLoadBillFrDt
GO

CREATE PROCEDURE dbo.UspGNOVASDLoadBillFrDt
( 	
	@cPOLNO		char(10),
	@cBILLPRDFR	CHAR(10)=''
)
AS
/*******************************************************************
	AIA CONFIDENTIAL MARCH 2000

	COMPASS 2000 USER STORED PROCEDURE

	STORED PROCEDURE USED FOR Load default header mapping
	
	AUTHOR		:	Hinson Liang
	DATE		:	01/15/2015
	
REVISION LOG:
PDCF		PROGRAMMER	DATE		CTRL No.	PURPOSE
------------------------------------------------------------------------------------------
			Hinson.L	01/15/2015				Initial
*********************************************************************/

SELECT @cBILLPRDFR = ISNULL(RTRIM(@cBILLPRDFR),'')


SELECT DISTINCT A.BILLPRDFR,A.BILLNO INTO #TEMP FROM TBILDETP A, TBILDETB B, TPOLICY C
WHERE C.POLNO = @cPOLNO
AND A.COMPCODE = C.COMPCODE
AND A.CLNTCODE = C.CLNTCODE
AND A.POLNO =C.POLNO
AND A.RCDSTS = 'A'
AND B.COMPCODE = A.COMPCODE
AND B.CLNTCODE = A.CLNTCODE
AND B.BILLNO = A.BILLNO
AND B.SUBOFFCODE = A.SUBOFFCODE
AND B.RCDSTS = 'A'
AND B.FMTBILLIND = 'O'
AND B.PAIDDATE IS NOT NULL
AND (A.BILLPRDFR=@cBILLPRDFR OR (@cBILLPRDFR = '' AND NOT EXISTS(SELECT * FROM TSTMPDUTYPYMT_TPATRX D
		WHERE D.POLNO = A.POLNO
		AND D.BILLPRDFR = A.BILLPRDFR
		AND D.RCDSTS = 'A'
		)))

SELECT DISTINCT A.BILLPRDFR,(SELECT RTRIM(B.BILLNO) + ',' FROM #TEMP B WHERE B.BILLPRDFR = A.BILLPRDFR FOR XML PATH('')) AS BILLNO INTO #RESULT
FROM #TEMP A

SELECT BILLPRDFR,CONVERT(CHAR(10),BILLPRDFR,101) AS BillFrom, LEFT(BILLNO,LEN(BILLNO)-1) AS BillList FROM #RESULT	--Date format MM/dd/yyyy
ORDER BY BILLPRDFR DESC

DROP TABLE #TEMP

RETURN


