IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.USPGNOVAUPDATEPLNDESC') AND sysstat & 0xf = 4)
	drop procedure dbo.USPGNOVAUPDATEPLNDESC
GO

SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER ON  
SET CONCAT_NULL_YIELDS_NULL ON 
SET ANSI_WARNINGS ON 
SET ANSI_PADDING ON
go

CREATE PROCEDURE dbo.USPGNOVAUPDATEPLNDESC
(@request_no		VARCHAR(30))
AS
BEGIN
/*******************************************************************
	COMPASS 2000 USER STORED PROCEDURE

	USPGNOVAUPDATEPLNDESC.SQL - Prepare TMEMPTPOL table for TMEMPTPOL_NOVA letter
        
        PROCESSING DETAILS:
        Prepare TMEMPTPOL table for TMEMPTPOL_NOVA letter
			
	AUTHOR      :     Issca Zhu
	DATE	    :     11/06/2014
	PIRNO	    :	  

	REVISION LOG:
	VERSION	  PIRNO		PROGRAMMER	REMARK		DATE		PURPOSE
        5.0	  NOVA		Issca Zhu				11/06/2014	Initial Version
********************************************************************/
/*error handling variable section */
DECLARE @ErrFrom	CHAR(20)
DECLARE @ErrMsg		CHAR(65)
DECLARE @ErrData	CHAR(45)
DECLARE @ErrCode        INT
DECLARE @StoreProcInd   CHAR(1)
DECLARE	@cMSGID		CHAR(5)
/*DECLARE VARIABLES AND CONSTANTS*/
DECLARE	@cACTIVE	CHAR(1)
DECLARE	@cDELETED	CHAR(1)
DECLARE	@cYES		CHAR(1)
DECLARE	@cNO		CHAR(1)
DECLARE @XML XML 
DECLARE	@CLNTCODE	CHAR(1)
DECLARE	@cCLNTCODE	CHAR(5)
DECLARE	@cPOLNO		CHAR(10)
DECLARE	@cCERTNO	VARCHAR(10)
DECLARE @cProgramID VARCHAR(60)
DECLARE	@EFFDATE	DATETIME
DECLARE	@cMEM		CHAR(3)
DECLARE	@cSUBOFFCODE CHAR(3)
DECLARE	@cCNTYCODE	CHAR(3)
DECLARE	@cBANKAC	NCHAR(80)
DECLARE	@cBANKBRNAME NCHAR(100)
DECLARE	@cBANKCODE	CHAR(4)
DECLARE	@cPAYEENAME NCHAR(128)
DECLARE	@cPRMRFBANKCODE CHAR(4)
DECLARE	@cPRMRFBANKACCT NCHAR(80)
DECLARE @cPRMRFBANKBRNAME NCHAR(128)

SELECT @cACTIVE = 'A'
SELECT @cMEM = 'MEM'

SELECT @XML = NovaXML FROM T_Nova_TXMLConvert where request_no = @request_no
SELECT  @cCLNTCODE = T.N.value('CLNTCODE[1]','varchar(20)') from  @XML.nodes('/form/TCLIENT/item') T(N) 
SELECT  @cPOLNO = T.N.value('POLNO[1]','varchar(10)') from  @XML.nodes('/form/TPOLICY/item') T(N) 


UPDATE	T1
SET		T1.BENAMTMB	= (T2.BENAMTMB/1000)*30
FROM	TPOLPDTBEN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
--AND		T1.BENCODE	= T2.BENCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		T2.PRODCODE  = '301C2' 
AND		T2.BENCODE='H04'
AND		T1.PRODCODE  = '301C2' 
AND		T1.BENCODE='H01'

UPDATE	T1
SET		T1.BENAMTMB	= (T2.BENAMTMB/1000)*1500
FROM	TPOLPDTBEN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
--AND		T1.BENCODE	= T2.BENCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		T2.PRODCODE  = '301C2' 
AND		T2.BENCODE='H04'
AND		T1.PRODCODE  = '301C2' 
AND		T1.BENCODE='H05'

UPDATE	T1
SET		T1.BENAMTMB	= (T2.BENAMTMB/1000)*1000
FROM	TPOLPDTBEN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
--AND		T1.BENCODE	= T2.BENCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		T2.PRODCODE  = '301C2' 
AND		T2.BENCODE='H04'
AND		T1.PRODCODE  = '301C2' 
AND		T1.BENCODE='H39'

UPDATE	T1
SET		T1.PLNDESC	= T2.PLNDESC
FROM	TPOLPDTPLN T1,
		TPOLPDT_NOVA T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T2.REQUESTNO = @request_no

UPDATE	T1
SET		T1.PLANLIMIT3	= T2.BENAMTMB
FROM	TPOLPDTPLN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		T1.PRODCODE NOT IN ('301C2','311S3')

UPDATE	T1
SET		T1.PLANLIMIT2	= T2.BENAMTMB
FROM	TPOLPDTPLN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		T1.PRODCODE IN ('311S3')


UPDATE	T1
SET		T1.BENLIMIT2	= T2.BENAMTMB
FROM	TPOLPDTBEN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
AND		T1.BENCODE	= T2.BENCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		(T2.PRODCODE  = '311S3' OR (T2.PRODCODE  = '301C2' AND T2.BENCODE='H01'))

UPDATE	T1
SET		T1.BENLIMIT3	= T2.BENAMTMB
FROM	TPOLPDTBEN T1,
		TPOLPDTBEN T2
WHERE	T1.POLNO	= T2.POLNO
AND		T1.PRODCODE	= T2.PRODCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.EFFDATE	= T2.EFFDATE
AND		T1.BENCODE	= T2.BENCODE
AND		T1.BENPLNCD = T2.BENPLNCD
AND		T1.POLNO	= @cPOLNO
AND		(T2.PRODCODE  IN ('201C1','211D1','211D2','211S5','214S1','301S1') OR (T2.PRODCODE  = '301C2' AND T2.BENCODE='H04')
OR (T2.PRODCODE  = '301C2' AND T2.BENCODE='H05') OR (T2.PRODCODE  = '301C2' AND T2.BENCODE='H39'))


EXIT_WINDOW:

	RETURN

END

SET ANSI_NULLS OFF 
SET QUOTED_IDENTIFIER OFF  
SET CONCAT_NULL_YIELDS_NULL OFF 
SET ANSI_WARNINGS OFF 
SET ANSI_PADDING OFF 
GO