--DROP TABLE NOVA.TNOVA_SDRequest_template

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('NOVA.TNOVA_SDRequest_template'))
BEGIN
	CREATE TABLE NOVA.TNOVA_SDRequest_template(
		FORM_SYSTEM_ID DECIMAL(18,0) NULL,
		NOVAREQNO varchar(30) NULL,
		ReqBy	CHAR(08) NULL,
		SubmitDATE	DATETIME NULL,
		ApproveDATE	DATETIME NULL,
		POLNO char(10) NULL,
		BILLPRDFR char(10) NULL,
		FILEPATH varchar(500) NULL

	)
END


--Add GROWTHDEF
IF NOT EXISTS (SELECT TC.NAME FROM DBO.SYSCOLUMNS TC WHERE TC.ID = OBJECT_ID('NOVA.TNOVA_SDRequest_template') AND TC.NAME = N'GROWTHDEF')
BEGIN
	ALTER TABLE NOVA.TNOVA_SDRequest_template ADD GROWTHDEF VARCHAR(20) NULL
END


IF NOT EXISTS (SELECT TC.NAME FROM DBO.SYSCOLUMNS TC WHERE TC.ID = OBJECT_ID('NOVA.TNOVA_SDRequest_template') AND TC.NAME = N'ASSIGNDATE')
BEGIN
	ALTER TABLE NOVA.TNOVA_SDRequest_template ADD ASSIGNDATE CHAR(10) NULL
END