
SELECT * INTO #TPOLPDT_TEMPLATE	FROM NOVA.TPOLPDT_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDT_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDT_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDT_TEMPLATE SELECT * FROM #TPOLPDT_TEMPLATE
UPDATE #TPOLPDT_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDT_TEMPLATE SELECT * FROM #TPOLPDT_TEMPLATE

SELECT * INTO #TPOLPDTH_TEMPLATE	FROM NOVA.TPOLPDTH_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTH_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTH_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTH_TEMPLATE SELECT * FROM #TPOLPDTH_TEMPLATE
UPDATE #TPOLPDTH_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTH_TEMPLATE SELECT * FROM #TPOLPDTH_TEMPLATE

SELECT * INTO #TPOLPDTADJ_TEMPLATE	FROM NOVA.TPOLPDTADJ_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTADJ_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTADJ_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTADJ_TEMPLATE SELECT * FROM #TPOLPDTADJ_TEMPLATE
UPDATE #TPOLPDTADJ_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTADJ_TEMPLATE SELECT * FROM #TPOLPDTADJ_TEMPLATE

SELECT * INTO #TPOLPDTBEN_TEMPLATE	FROM NOVA.TPOLPDTBEN_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTBEN_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTBEN_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTBEN_TEMPLATE SELECT * FROM #TPOLPDTBEN_TEMPLATE
UPDATE #TPOLPDTBEN_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTBEN_TEMPLATE SELECT * FROM #TPOLPDTBEN_TEMPLATE

SELECT * INTO #TPOLPDTCOM_TEMPLATE	FROM NOVA.TPOLPDTCOM_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTCOM_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTCOM_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTCOM_TEMPLATE SELECT * FROM #TPOLPDTCOM_TEMPLATE
UPDATE #TPOLPDTCOM_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTCOM_TEMPLATE SELECT * FROM #TPOLPDTCOM_TEMPLATE

SELECT * INTO #TPOLPDTCOV_TEMPLATE	FROM NOVA.TPOLPDTCOV_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTCOV_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTCOV_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTCOV_TEMPLATE SELECT * FROM #TPOLPDTCOV_TEMPLATE
UPDATE #TPOLPDTCOV_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTCOV_TEMPLATE SELECT * FROM #TPOLPDTCOV_TEMPLATE

SELECT * INTO #TPOLPDTLIMIT_TEMPLATE	FROM NOVA.TPOLPDTLIMIT_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTLIMIT_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTLIMIT_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTLIMIT_TEMPLATE SELECT * FROM #TPOLPDTLIMIT_TEMPLATE
UPDATE #TPOLPDTLIMIT_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTLIMIT_TEMPLATE SELECT * FROM #TPOLPDTLIMIT_TEMPLATE

SELECT * INTO #TPOLPDTPLN_TEMPLATE	FROM NOVA.TPOLPDTPLN_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTPLN_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTPLN_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTPLN_TEMPLATE SELECT * FROM #TPOLPDTPLN_TEMPLATE
UPDATE #TPOLPDTPLN_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTPLN_TEMPLATE SELECT * FROM #TPOLPDTPLN_TEMPLATE


SELECT * INTO #TPOLPDTPLNH_TEMPLATE	FROM NOVA.TPOLPDTPLNH_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTPLNH_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTPLNH_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTPLNH_TEMPLATE SELECT * FROM #TPOLPDTPLNH_TEMPLATE
UPDATE #TPOLPDTPLNH_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTPLNH_TEMPLATE SELECT * FROM #TPOLPDTPLNH_TEMPLATE

SELECT * INTO #TPOLPDTPRM_TEMPLATE	FROM NOVA.TPOLPDTPRM_TEMPLATE where form_system_id='0'
UPDATE  NOVA.TPOLPDTPRM_TEMPLATE SET form_system_id='20264' where form_system_id='0' 
UPDATE #TPOLPDTPRM_TEMPLATE SET form_system_id='30286'
INSERT  NOVA.TPOLPDTPRM_TEMPLATE SELECT * FROM #TPOLPDTPRM_TEMPLATE
UPDATE #TPOLPDTPRM_TEMPLATE SET form_system_id='30288'
INSERT  NOVA.TPOLPDTPRM_TEMPLATE SELECT * FROM #TPOLPDTPRM_TEMPLATE

UPDATE NOVA.TPOLPDT_TEMPLATE SET BILLTODATE = NULL


