
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='30'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='001'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='60'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='002'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='70'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='003'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='80'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='004'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='100' WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='005'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='30'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='006'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='60'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='007'


UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='30'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='008'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='60'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='009'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='70'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='010'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='80'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='011'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='100' WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='012'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='30'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='013'
UPDATE NOVA.TPOLPDTBEN_TEMPLATE SET OOPIND='Y', SRVTYPE='D',SRVNUM='180',SRVUNIT='B',BENAMTMB='60'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD='014'


UPDATE NOVA.TPOLPDTPLNH_TEMPLATE SET USERDEFINED1 = 'SHIP PLAN'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='211S3' AND BENPLNCD<=007
UPDATE NOVA.TPOLPDTPLNH_TEMPLATE SET USERDEFINED1 = 'NON-SHIP PLAN'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='211S3' AND BENPLNCD>007

UPDATE NOVA.TPOLPDTPLNH_TEMPLATE SET USERDEFINED1 = 'SHIP PLAN'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S2' AND BENPLNCD<=007
UPDATE NOVA.TPOLPDTPLNH_TEMPLATE SET USERDEFINED1 = 'NON-SHIP PLAN'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S2' AND BENPLNCD>007

UPDATE NOVA.TPOLPDTPLNH_TEMPLATE SET USERDEFINED1 = 'SHIP PLAN'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD<=007
UPDATE NOVA.TPOLPDTPLNH_TEMPLATE SET USERDEFINED1 = 'NON-SHIP PLAN'  WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S3' AND BENPLNCD>007


UPDATE NOVA.TPOLPDTCOV_TEMPLATE  SET MBEAGEMAX = '60' WHERE PKGPRDCD='GCPA4' AND PRODCODE='311S2'
