
--DROP TABLE TNOVA_SDPremSum

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.TNOVA_SDPremSum'))
BEGIN
	CREATE TABLE dbo.TNOVA_SDPremSum(
		NOVAREQNO	VARCHAR(30)	NOT NULL,
		POLNO	CHAR(10)	NOT NULL,
		BILLPRDFR	CHAR(10)	NOT NULL,
		PRODCODE	CHAR(5)	NOT NULL,
		PRODSHORT	CHAR(10) NULL,
		STATE	CHAR(03)	NOT NULL,
		ApportionPCT	DECIMAL(5,4) NULL,
		StmpDutyPCT	DECIMAL(5,4) NULL,
		CALCBASIS	CHAR(03) NULL,
		NETOFFPCT	DECIMAL(6,4) NULL,
		PREMPAID	DECIMAL(13,2) NULL,
		PREMANNGROW	DECIMAL(13,2) NULL,
		FYRENCODE	CHAR(01) NULL,
		STMPDUTYPAID	Decimal(13,2) NULL
	) 
	CREATE CLUSTERED INDEX IDX_TNOVA_SDPremSum ON dbo.TNOVA_SDPremSum (NOVAREQNO, POLNO, BILLPRDFR, STATE , PRODCODE)
END

