--DROP TABLE TNOVA_SDHdrMap
--20150313 asnpgn7

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.TNOVA_SDHdrMap'))
BEGIN
	CREATE TABLE dbo.TNOVA_SDHdrMap(
		NOVAREQNO	VARCHAR(30)	NOT NULL,
		NOVAHDRNAME	VARCHAR(100) NOT NULL,
		HDRNAME	VARCHAR(100) NULL,
		FIELDNAME	VARCHAR(100) NULL,
		PRODCODE	CHAR(05) NULL,
		HDRINDEX	DECIMAL(12,0)	NULL

		CONSTRAINT [PK_TNOVA_SDHdrMap] PRIMARY KEY CLUSTERED 
		(
			[NOVAREQNO],NOVAHDRNAME
		)
	) 

END

