--DROP TABLE TNBBSMap

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.TNBBSMap'))
BEGIN
	CREATE TABLE [dbo].[TNBBSMap](
		ReportType	CHAR(10) NOT NULL,
		BenGroup	CHAR(10) NOT NULL,
		ItemID	DECIMAL(20,0) NOT NULL,
		TitleColIdx	INT NOT NULL,
		ValueColIdx	INT NOT NULL,
		ParentID	DECIMAL(20,0) NOT NULL,
		BenMatch	CHAR(10) NOT NULL,
		ItemName_ENG	NVARCHAR(1000) NULL,
		ItemName_LOC1	NVARCHAR(1000) NULL,
		ItemName_LOC2	NVARCHAR(1000) NULL,
		TitleClass	VARCHAR(10) NULL,
		RemarkCode	NVARCHAR(1000) NULL,
		DataSQLMain	NVARCHAR(max) NULL,
		DataSQL_Header	NVARCHAR(200) NULL,
		DataSQL_Item_Crt	NVARCHAR(max) NULL,
		ValueClass	VARCHAR(10) NULL,
		Value_ENG	NVARCHAR(max) NULL,
		Value_LOC1	NVARCHAR(max) NULL,
		Value_LOC2	NVARCHAR(max) NULL,
		PRODCODE	CHAR(05) NULL,
		BENCODE	CHAR(03) NULL,
		Editable	CHAR(01)	 NULL,
		Mergeable	CHAR(01)	 NULL,


	 CONSTRAINT [PK_TNBBSMap] PRIMARY KEY CLUSTERED 
	(
		[ReportType] ASC,
		BenGroup ASC,
		[ItemID] ASC,
		TitleColIdx ASC,
		ValueColIdx ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END

