--DROP TABLE TNovaSDFieldLst

IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.TNovaSDFieldLst'))
BEGIN
	CREATE TABLE dbo.TNovaSDFieldLst(
		NEWMEMDEF	INT NOT NULL,
		FieldName	VARCHAR(100) NOT NULL,
		FieldDesc	VARCHAR(100) NOT NULL,
		SelProdInd	CHAR(01) NOT NULL,
		OptionalInd	CHAR(01) NULL,
		SortOrder	int
	) 
	CREATE CLUSTERED INDEX IDX_TNovaSDFieldLst ON dbo.TNovaSDFieldLst (NEWMEMDEF,FieldName)
END

