DELETE TRptRemark

INSERT TRptRemark VALUES('PS0001','<h3>Remarks:</h3><div><span style="font:normal 800 16px Arial;">N.B.:</span><div style="position:relative;left:30px;display:inline">dis=disability</div></div><div style="position:relative;left:73px">yr=policy year</div>')
INSERT TRptRemark VALUES('PS0002','The specified maximum number of days set forth in this benefit are included in Room & Board Benefit.')
INSERT TRptRemark VALUES('PS0003','Surgical Supplies shall be payable under Other Hospital Services.')
INSERT TRptRemark VALUES('PS0004','Must be referred by a registered medical practitioner in western medicine.')
INSERT TRptRemark VALUES('PS0005','Overall maximum visits are @opmaxvisit per policy year.')
INSERT TRptRemark VALUES('PS0007','@waive_OPSC_rmk')
INSERT TRptRemark VALUES('PS0008','China Assist Card, accepted by over 100 high quality hospitals in Mainland China, provides deposit guarantee services for hospitals admission (if necessary) to insured members traveling in China less than 90 days.')
INSERT TRptRemark VALUES('PS0009','Basic Diagnostic Testing includes basic diagnostic imaging (X-Ray, mammograms, ultrasound).  Advanced diagnostic imaging (MRI, CT scans, nuclear medicine) shall be payable under Other Hospital Services.')
INSERT TRptRemark VALUES('PSMC00','Network Hospitalization Benefits require prior authorization (for emergency, notification should be made within 24 hours).')
INSERT TRptRemark VALUES('PSMC01','Hospitalization Benefits do not require prior authorization. ')
INSERT TRptRemark VALUES('PSMC02','Overall maximum is  @opmaxvisit  visits per member per Policy Year.')
INSERT TRptRemark VALUES('PSMC03','Basic Diagnostic Testing includes basic diagnostic imaging (X-Ray, mammograms, ultrasound).  Advanced diagnostic imaging (MRI, CT scans, nuclear medicine) shall be payable under Other Hospital Services and for Network Benefit, prior authorization by the Company shall be required.')
INSERT TRptRemark VALUES('PSMC04','Prior Authorization by the Company or AIAS Provider shall be required.')
INSERT TRptRemark VALUES('PSMC05','Referral letter is required.')
