IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID('dbo.USPGNOVAGENTBANKACCTINFO') AND sysstat & 0xf = 4)
	drop procedure dbo.USPGNOVAGENTBANKACCTINFO
GO

SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER ON  
SET CONCAT_NULL_YIELDS_NULL ON 
SET ANSI_WARNINGS ON 
SET ANSI_PADDING ON
GO 
CREATE PROCEDURE dbo.USPGNOVAGENTBANKACCTINFO
(@request_no		VARCHAR(30))
AS
BEGIN
/*******************************************************************
	COMPASS 2000 USER STORED PROCEDURE

	USPGNOVAGENTBANKACCTINFO.SQL - Prepare TMEMPTPOL table for TMEMPTPOL_NOVA letter
        
        PROCESSING DETAILS:
        Prepare TMEMPTPOL table for TMEMPTPOL_NOVA letter
			
	AUTHOR      :     Issca Zhu
	DATE	    :     11/06/2014
	PIRNO	    :	  

	REVISION LOG:
	VERSION	  PIRNO		PROGRAMMER	REMARK		DATE		PURPOSE
        5.0	  NOVA		Issca Zhu				11/06/2014	Initial Version
********************************************************************/
/*error handling variable section */
DECLARE @ErrFrom	CHAR(20)
DECLARE @ErrMsg		CHAR(65)
DECLARE @ErrData	CHAR(45)
DECLARE @ErrCode        INT
DECLARE @StoreProcInd   CHAR(1)
DECLARE	@cMSGID		CHAR(5)
/*DECLARE VARIABLES AND CONSTANTS*/
DECLARE	@cACTIVE	CHAR(1)
DECLARE	@cDELETED	CHAR(1)
DECLARE	@cYES		CHAR(1)
DECLARE	@cNO		CHAR(1)
DECLARE @XML XML 
DECLARE	@CLNTCODE	CHAR(1)
DECLARE	@cCLNTCODE	CHAR(5)
DECLARE	@cPOLNO		CHAR(10)
DECLARE	@cCERTNO	VARCHAR(10)
DECLARE @cProgramID VARCHAR(60)
DECLARE	@EFFDATE	DATETIME
DECLARE	@cMEM		CHAR(3)
DECLARE	@cSUBOFFCODE CHAR(3)
DECLARE	@cCNTYCODE	CHAR(5)
DECLARE	@cBANKAC	NCHAR(80)
DECLARE	@cBANKBRNAME NCHAR(100)
DECLARE	@cBANKCODE	CHAR(4)
DECLARE	@cPAYEENAME NCHAR(128)
DECLARE	@cPRMRFBANKCODE CHAR(4)
DECLARE	@cPRMRFBANKACCT NCHAR(80)
DECLARE @cPRMRFBANKBRNAME NCHAR(128)

SELECT @cACTIVE = 'A'
SELECT @cMEM = 'MEM'

SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER ON  
SET CONCAT_NULL_YIELDS_NULL ON 
SET ANSI_WARNINGS ON 
SET ANSI_PADDING ON

SELECT @XML = NovaXML FROM T_Nova_TXMLConvert where request_no = @request_no
SELECT  @cCLNTCODE = T.N.value('CLNTCODE[1]','varchar(20)') from  @XML.nodes('/form/TCLIENT/item') T(N) 
--SELECT  @cSUBOFFCODE = T.N.value('SUBOFFCODE[1]','varchar(20)') from  @XML.nodes('/form/TBANKACCTINFO/item') T(N) 
SELECT  @cPOLNO = T.N.value('POLNO[1]','varchar(10)') from  @XML.nodes('/form/TPOLICY/item') T(N) 

declare CUR_GENBANKCYCLE cursor for
SELECT CLNTCODE,SUBOFFCODE,PAYEENAME,BANKCODE,BANKAC,BANKBRNAME,PRMRFBANKCODE,PRMRFBANKACCT,PRMRFBANKBRNAME 
FROM TCLNTSUB WHERE CLNTCODE=@cCLNTCODE AND RCDSTS = @cACTIVE
open CUR_GENBANKCYCLE

FETCH NEXT FROM CUR_GENBANKCYCLE INTO @cCLNTCODE,@cSUBOFFCODE,@cPAYEENAME,@cBANKCODE,@cBANKAC,@cBANKBRNAME,@cPRMRFBANKCODE,@cPRMRFBANKACCT,@cPRMRFBANKBRNAME
WHILE (@@FETCH_STATUS = 0)
BEGIN
	
	--NOVA-54 BEGIN

		--SELECT @cCNTYCODE=CITYCODE FROM TBANKACCTINFO WHERE CLNTCODE=@cCLNTCODE AND SUBOFFCODE=@cSUBOFFCODE AND SEQNO = 999999999

		SELECT @cCNTYCODE=T.b.value('CITYCODE[1]','varchar(5)') from @XML.nodes('/form/TBANKACCTINFO/item') T(b)  
		WHERE T.b.value('SUBOFFCODE[1]','varchar(3)') = @cSUBOFFCODE AND T.b.value('CLNTCODE[1]','varchar(5)') = @cCLNTCODE

	--NOVA-54 END

		IF @cSUBOFFCODE = '100'
		BEGIN

			IF NOT EXISTS(SELECT 1 FROM TBANKACCTINFO WHERE CLNTCODE = @cCLNTCODE AND SUBOFFCODE IS NULL AND BANKAC=@cBANKAC)
			BEGIN
				INSERT  TBANKACCTINFO (SEQNO,BANKAC,BANKCODE,PAYEENAME,CITYCODE,BANKBRANCH,CLNTCODE,CERTNO,SUBOFFCODE,PROVIDERCODE,RCDSTS,RCDUSRID,RCDDTSTMP)
				SELECT  MAX(SEQNO)+1,@cBANKAC,@cBANKCODE,@cPAYEENAME,@cCNTYCODE,@cBANKBRNAME,@cCLNTCODE,NULL,NULL,NULL,'A','NOVAPROC',GETDATE()
				FROM	TBANKACCTINFO

				INSERT  TBANKACCTINFO (SEQNO,BANKAC,BANKCODE,PAYEENAME,CITYCODE,BANKBRANCH,CLNTCODE,CERTNO,SUBOFFCODE,PROVIDERCODE,RCDSTS,RCDUSRID,RCDDTSTMP)
				SELECT  MAX(SEQNO)+1,@cPRMRFBANKACCT,@cPRMRFBANKCODE,@cPAYEENAME,@cCNTYCODE,@cPRMRFBANKBRNAME,@cCLNTCODE,NULL,NULL,NULL,'A','NOVAPROC',GETDATE()
				FROM	TBANKACCTINFO
			END
	
		END
		

		IF NOT EXISTS(SELECT 1 FROM TBANKACCTINFO WHERE CLNTCODE = @cCLNTCODE AND SUBOFFCODE = @cSUBOFFCODE AND BANKAC=@cBANKAC AND SEQNO <> 999999999)
		BEGIN

			INSERT  TBANKACCTINFO (SEQNO,BANKAC,BANKCODE,PAYEENAME,CITYCODE,BANKBRANCH,CLNTCODE,CERTNO,SUBOFFCODE,PROVIDERCODE,RCDSTS,RCDUSRID,RCDDTSTMP)
			SELECT  MAX(SEQNO)+1,@cBANKAC,@cBANKCODE,@cPAYEENAME,@cCNTYCODE,@cBANKBRNAME,@cCLNTCODE,NULL,@cSUBOFFCODE,NULL,'A','NOVAPROC',GETDATE()
			FROM	TBANKACCTINFO

			INSERT  TBANKACCTINFO (SEQNO,BANKAC,BANKCODE,PAYEENAME,CITYCODE,BANKBRANCH,CLNTCODE,CERTNO,SUBOFFCODE,PROVIDERCODE,RCDSTS,RCDUSRID,RCDDTSTMP)
			SELECT  MAX(SEQNO)+1,@cPRMRFBANKACCT,@cPRMRFBANKCODE,@cPAYEENAME,@cCNTYCODE,@cPRMRFBANKBRNAME,@cCLNTCODE,NULL,@cSUBOFFCODE,NULL,'A','NOVAPROC',GETDATE()
			FROM	TBANKACCTINFO
		END
	
SELECT @ErrCode = @@error
IF @ErrCode <> 0
BEGIN
	--SELECT @cRETCODE = '9999'
	
	INSERT T_Nova_ErrlogTran (RequestNo,ProgramID,ERRORLOG,RCDUSRID,RCDDTSTMP) 
	VALUES(@request_no,@cProgramID,'insert temp table TBANKACCTINFO error','NOVAPROC',GETDATE())
	
	GOTO EXIT_WINDOW
END	


FETCH NEXT FROM CUR_GENBANKCYCLE INTO @cCLNTCODE,@cSUBOFFCODE,@cPAYEENAME,@cBANKCODE,@cBANKAC,@cBANKBRNAME,@cPRMRFBANKCODE,@cPRMRFBANKACCT,@cPRMRFBANKBRNAME
END

CLOSE CUR_GENBANKCYCLE 
DEALLOCATE CUR_GENBANKCYCLE

DELETE FROM TBANKACCTINFO WHERE SEQNO = 999999999 AND CLNTCODE=@cCLNTCODE 

EXIT_WINDOW:

SET ANSI_NULLS OFF 
SET QUOTED_IDENTIFIER OFF  
SET CONCAT_NULL_YIELDS_NULL OFF 
SET ANSI_WARNINGS OFF 
SET ANSI_PADDING OFF 

	RETURN

END

SET ANSI_NULLS OFF 
SET QUOTED_IDENTIFIER OFF  
SET CONCAT_NULL_YIELDS_NULL OFF 
SET ANSI_WARNINGS OFF 
SET ANSI_PADDING OFF 
GO