
DELETE  FROM TSYSPARMH WHERE PARMDESC='NOVASP' AND PARMTYPE='30328'
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'1',N'30328',N'USPGNOVAGENTBANKACCTINFO',SUSER_SNAME(),GETDATE())
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'2',N'30328',N'USPGNOVAGENTPOLFINCL',SUSER_SNAME(),GETDATE())
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'3',N'30328',N'USPGNOVAGENTMEMPTPOL',SUSER_SNAME(),GETDATE())
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'4',N'30328',N'USPGNOVAGENTUHCMEMBERID',SUSER_SNAME(),GETDATE())
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'5',N'30328',N'USPGNOVAUPDATEPLNDESC',SUSER_SNAME(),GETDATE())
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'0',N'30328',N'USPGNOVAGENTPOLPDTFLAK',SUSER_SNAME(),GETDATE())
INSERT TSYSPARMH(PARMDESC,PARMVALUE,PARMTYPE,VALUEUSAGE,RCDUSRID,RCDDTSTMP)  VALUES(N'NOVASP',N'6',N'30328',N'USPGNOVABENAMTMB',SUSER_SNAME(),GETDATE())



DELETE FROM T_NOVA_compassprocess WHERE form_system_id='30328'

INSERT T_NOVA_compassprocess(form_system_id,current_node_Id,process_sp,error_code)  VALUES(N'30328',N'28',N'USPGNOVAAnalyseXML',N'E004')
